name: jest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  markdownlint:
    name: jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run test
        run: yarn test
